version: '3.8'

services:
  db:
    image: postgres:15.3
    restart: always
    container_name: previplus-db
    environment:
      POSTGRES_USER: namas
      POSTGRES_PASSWORD: namas
      POSTGRES_DB: previplus
    ports:
      - "5432:5432"
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data
      - ./backend/docker-init:/docker-entrypoint-initdb.d
    networks:
      - previplus-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: previplus-backend
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: namas
      DB_PASSWORD: namas
      DB_NAME: previplus
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - previplus-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    container_name: previplus-frontend
    ports:
      - "8080:80" # Mapea el puerto 80 del contenedor al puerto 8080 del host
    depends_on:
      - backend
    networks:
      - previplus-network

networks:
  previplus-network:
    driver: bridge