const { EntitySchema } = require("typeorm");

module.exports = new EntitySchema({
    name: "ArchivoPrevired",
    tableName: "archivo_previred",
    columns: {
        id: { primary: true, type: "int", generated: true },
        rut: { type: "varchar", length: 11, nullable: false, default: "", comment: "Campo 1 RUT del trabajador" },
        dv: { type: "varchar", length: 1, nullable: false, default: "", comment: "Campo 2 DV del trabajador" },
        patlastname: { type: "varchar", length: 30, nullable: false, default: "", comment: "Campo 3 Apellido paterno del trabajador" },
        matlastname: { type: "varchar", length: 30, nullable: true, default: "", comment: "Campo 4 Apellido materno del trabajador" },
        names: { type: "varchar", length: 30, nullable: false, default: "", comment: "Campo 5 Nombres del trabajador" },
        genero: { type: "varchar", length: 1, nullable: false, default: "", comment: "Campo 6 Género del trabajador" },
        nationality: { type: "int", nullable: false, default: 0, comment: "Campo 7 Nacionalidad del trabajador" },
        tipoPago: { type: "int", nullable: false, default: 0, comment: "Campo 8 Tipo de pago" },
        mesRemuneracion: { type: "varchar", length: 6, nullable: false, default: "", comment: "Campo 9 Período de pago" },
        condicional: { type: "varchar", length: 6, nullable: true, default: "", comment: "Campo 10 No implementado"},
        regimenPrevisional: { type: "varchar", length: 3, nullable: false, default: "", comment: "Campo 11 Regimen previsional" },
        tipoTrabajador: { type: "int", nullable: false, default: 0, comment: "Campo 12 Tipo de trabajador" },
        diasTrabajados: { type: "int", nullable: false, default: 0, comment: "Campo 13 Días trabajados" },
        tipoLinea: { type: "varchar", length: 2, nullable: false, default: "", comment: "Campo 14 Tipo de línea de cotización" },
        codigoMovPersonal: { type: "int", nullable: false, default: 0, comment: "Campo 15 Código de movimiento personal" },
        condicional: { type: "varchar", length: 10, nullable: true, default: "", comment: "Campo 16 No implementado"},
        condicional: { type: "varchar", length: 10, nullable: true, default: "", comment: "Campo 17 No implementado"},
        tramoAsignacionFamiliar: { type: "varchar", length: 1, nullable: true, default: "", comment: "Campo 18 Tramo asignación familiar" },
        condicional: { type: "int", nullable: true, default: 0, comment: "Campo 19 No implementado"},
        condicional: { type: "int", nullable: true, default: 0, comment: "Campo 20 No implementado"},
        campo21_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 21 No implementado"},
        campo22_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 22 No implementado"},
        campo23_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 23 No implementado"},
        campo24_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 24 No implementado"},
        campo25_condicional: { type: "varchar", length: 1, nullable: true, default: "", comment: "Campo 25 No implementado"},
        codigoAFP: { type: "int", nullable: true, default: 0, comment: "Campo 26 Código AFP" },
        sueldoImponibleAfp: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 27 Sueldo imponible AFP" },
        cotizacionObligatoriaAFP: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 28 Valor cotización AFP" },
        cotizacionSIS: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 29 Valor cotización SIS" },
        campo30_condicional: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 30 No implementado"},
        campo31_condicional: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 31 No implementado"},
        campo32_condicional: { type: "decimal", precision: 5, scale: 2, nullable: true, default: 0, comment: "Campo 32 No implementado"},
        campo33_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 33 No implementado"},
        campo34_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 34 No implementado"},
        campo35_condicional: { type: "varchar", length: 10, nullable: true, default: "", comment: "Campo 35 No implementado"},
        campo36_condicional: { type: "varchar", length: 10, nullable: true, default: "", comment: "Campo 36 No implementado"},
        campo37_condicional: { type: "varchar", length: 40, nullable: true, default: "", comment: "Campo 37 No implementado"},
        campo38_condicional: { type: "decimal", precision: 5, scale: 2, nullable: true, default: 0, comment: "Campo 38 No implementado"},
        campo39_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 39 No implementado"},
        campo40_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 40 No implementado"},
        campo41_condicional: { type: "varchar", length: 20, nullable: true, default: "", comment: "Campo 41 No implementado"},
        campo42_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 42 No implementado"},
        campo43_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 43 No implementado"},
        campo44_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 44 No implementado"},
        campo45_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 45 No implementado"},
        campo46_condicional: { type: "varchar", length: 20, nullable: true, default: "", comment: "Campo 46 No implementado"},
        campo47_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 47 No implementado"},
        campo48_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 48 No implementado"},
        campo49_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 49 No implementado"},
        campo50_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 50 No implementado"},
        campo51_condicional: { type: "varchar", length: 1, nullable: true, default: "", comment: "Campo 51 No implementado"},
        campo52_condicional: { type: "varchar", length: 30, nullable: true, default: "", comment: "Campo 52 No implementado"},
        campo53_condicional: { type: "varchar", length: 30, nullable: true, default: "", comment: "Campo 53 No implementado"},
        campo54_condicional: { type: "varchar", length: 30, nullable: true, default: "", comment: "Campo 54 No implementado"},
        campo55_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 55 No implementado"},
        campo56_condicional: { type: "varchar", length: 10, nullable: true, default: "", comment: "Campo 56 No implementado"},
        campo57_condicional: { type: "varchar", length: 10, nullable: true, default: "", comment: "Campo 57 No implementado"},
        campo58_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 58 No implementado"},
        campo59_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 59 No implementado"},
        campo60_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 60 No implementado"},
        campo61_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 61 No implementado"},
        campo62_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 62 No implementado"},
        campo63_condicional: { type: "decimal", precision: 5, scale: 2, nullable: true, default: 0, comment: "Campo 63 No implementado"},
        sueldoImponibleSalud: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 64 Sueldo imponible salud" },
        campo65_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 65 No implementado"},
        campo66_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 66 No implementado"},
        campo67_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 67 No implementado"},
        campo68_condicional: { type: "decimal", precision: 5, scale: 2, nullable: true, default: 0, comment: "Campo 68 No implementado"},
        campo69_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 69 No implementado"},
        cotizacionFonasa: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 70 Calculo 7% Fonasa" },
        cotizacionISL: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 71 Mutualidad ISL" },
        campo72_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 72 No implementado"},
        campo73_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 73 No implementado" },
        campo74_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 74 No implementado"},
        codigoSalud: { type: "int", nullable: true, default: 0, comment: "Campo 75 Código ISAPRE" },
        numeroFUN: { type: "varchar", length: 16, nullable: true, default: "", comment: "Campo 76 Número de contrato salud" },
        sueldoImponibleSaludIsapre: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 77 Renta imponible trabajador" },
        tipoMoneda: { type: "int", nullable: true, default: 0, comment: "Campo 78 Tipo de moneda" },
        cotizacionPactada: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 79 Cotización pactada" },
        cotizacionIsapre: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 80 Cotización 7% por ciento para ISAPRE" },
        cotizacionAdicionalIsapre: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 81 Diferencia 7% por ciento para ISAPRE" },
        campo82_condicional: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 82 No implementado"},
        codigoCCAF: { type: "int", nullable: true, default: 0, comment: "Campo 83 Código CCAF" },
        sueldoImponibleCcaf: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 84 Renta imponible CCAF" },
        creditosPersonalesCcaf: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 85 Créditos personales CCAF" },
        descuentoDental: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 86 Descuento dental CCAF" },
        descuentoLeasing: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 87 Descuentos leasing CCAF" },
        descuentoSeguroVida: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 88 Descuento seguro de vida CCAF" },
        otrosDescuentos: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 89 Otros descuentos CCAF" },
        cotizacionNoIsapre: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 90 Cotización CCAF no Isapre" },
        descuentoCargasFamiliares: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment:"Campo 91 Descuentos cargas familiares" },
        campo92_condicional: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 92 No implementado"},
        campo93_condicional: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 93 No implementado"},
        campo94_condicional: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 94 No implementado"},
        campo95_condicional: { type: "varchar", length: 20, nullable: true, default: "", comment: "Campo 95 No implementado"},
        codigoMutualidad: { type: "int", nullable: true, default: 0, comment: "Campo 96 Código de la mutualidad" },
        sueldoImponibleMutual: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 97 Renta imponible mutual" },
        cotizacionMutual: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 98 Calculo mutual" },
        campo99_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 99 No implementado"},
        sueldoImponibleSegCensantia: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 100 Renta imponible seg ceáster" },
        aporteTrabajadorCesantia: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 101 Aporte trabajador seg ceáster" },
        aporteEmpleadorCesantia: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0, comment: "Campo 102 Aporte empleador seg ceáster" },
        campo103_condicional: { type: "int", nullable: true, default: 0, comment: "Campo 103 No implementado"},
        campo104_condicional: { type: "varchar", length: 1, nullable: true, default: "", comment: "Campo 104 No implementado"},
        campo105_condicional: { type: "varchar", length: 20, nullable: true, default: "", comment: "Campo 105 No implementado"},
    },
    relations: {
        usuario: {
            target: "Usuario",
            type: "many-to-one",
            joinColumn: {
                name: "usuario_id"
            },
            onDelete: "CASCADE"
        },
        negocio: {
            target: "Negocio",
            type: "many-to-one",
            joinColumn: {
                name: "negocio_id"
            },
            onDelete: "CASCADE"
        }
    }
});