const { EntitySchema } = require("typeorm");

module.exports = new EntitySchema({
    name: "ArchivoPrevired",
    tableName: "archivo_previred",
    columns: {
        id: { primary: true, type: "int", generated: true },

        campo1_rut: { type: "varchar", length: 11, nullable: false, default: "" },
        campo2_dv: { type: "varchar", length: 1, nullable: false, default: "" },
        campo3_ap_paterno: { type: "varchar", length: 30, nullable: false, default: "" },
        campo4_ap_materno: { type: "varchar", length: 30, nullable: true, default: "" },
        campo5_nombres: { type: "varchar", length: 30, nullable: false, default: "" },
        campo6_genero: { type: "varchar", length: 1, nullable: false, default: "" },
        campo7_nacionalidad: { type: "int", nullable: false, default: 0 },
        campo8_tipo_pago: { type: "int", nullable: false, default: 0 },
        campo9_periodo: { type: "varchar", length: 6, nullable: false, default: "" },
        campo10_condicional: { type: "varchar", length: 6, nullable: true, default: "" },
        campo11_regimen_previsional: { type: "varchar", length: 3, nullable: false, default: "" },
        campo12_tipo_trabajador: { type: "int", nullable: false, default: 0 },
        campo13_dias_trabajados: { type: "int", nullable: false, default: 0 },
        campo14_tipo_linea: { type: "varchar", length: 2, nullable: false, default: "" },
        campo15_codigo_movimiento_personal: { type: "int", nullable: false, default: 0 },
        campo16_condicional: { type: "varchar", length: 10, nullable: true, default: "" },
        campo17_condicional: { type: "varchar", length: 10, nullable: true, default: "" },
        campo18_tramo_asig_fam: { type: "varchar", length: 1, nullable: true, default: "" },
        campo19_condicional: { type: "int", nullable: true, default: 0 },
        campo20_condicional: { type: "int", nullable: true, default: 0 },
        campo21_condicional: { type: "int", nullable: true, default: 0 },
        campo22_condicional: { type: "int", nullable: true, default: 0 },
        campo23_condicional: { type: "int", nullable: true, default: 0 },
        campo24_condicional: { type: "int", nullable: true, default: 0 },
        campo25_condicional: { type: "varchar", length: 1, nullable: true, default: "" },
        campo26_codigo_afp: { type: "int", nullable: true, default: 0 },
        campo27_imp_afp: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo28_calculo_pago_afp: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo29_calculo_sis: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo30_condicional: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo31_condicional: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo32_condicional: { type: "decimal", precision: 5, scale: 2, nullable: true, default: 0 },
        campo33_condicional: { type: "int", nullable: true, default: 0 },
        campo34_condicional: { type: "int", nullable: true, default: 0 },
        campo35_condicional: { type: "varchar", length: 10, nullable: true, default: "" },
        campo36_condicional: { type: "varchar", length: 10, nullable: true, default: "" },
        campo37_condicional: { type: "varchar", length: 40, nullable: true, default: "" },
        campo38_condicional: { type: "decimal", precision: 5, scale: 2, nullable: true, default: 0 },
        campo39_condicional: { type: "int", nullable: true, default: 0 },
        campo40_condicional: { type: "int", nullable: true, default: 0 },
        campo41_condicional: { type: "varchar", length: 20, nullable: true, default: "" },
        campo42_condicional: { type: "int", nullable: true, default: 0 },
        campo43_condicional: { type: "int", nullable: true, default: 0 },
        campo44_condicional: { type: "int", nullable: true, default: 0 },
        campo45_condicional: { type: "int", nullable: true, default: 0 },
        campo46_condicional: { type: "varchar", length: 20, nullable: true, default: "" },
        campo47_condicional: { type: "int", nullable: true, default: 0 },
        campo48_condicional: { type: "int", nullable: true, default: 0 },
        campo49_condicional: { type: "int", nullable: true, default: 0 },
        campo50_condicional: { type: "int", nullable: true, default: 0 },
        campo51_condicional: { type: "varchar", length: 1, nullable: true, default: "" },
        campo52_condicional: { type: "varchar", length: 30, nullable: true, default: "" },
        campo53_condicional: { type: "varchar", length: 30, nullable: true, default: "" },
        campo54_condicional: { type: "varchar", length: 30, nullable: true, default: "" },
        campo55_condicional: { type: "int", nullable: true, default: 0 },
        campo56_condicional: { type: "varchar", length: 10, nullable: true, default: "" },
        campo57_condicional: { type: "varchar", length: 10, nullable: true, default: "" },
        campo58_condicional: { type: "int", nullable: true, default: 0 },
        campo59_condicional: { type: "int", nullable: true, default: 0 },
        campo60_condicional: { type: "int", nullable: true, default: 0 },
        campo61_condicional: { type: "int", nullable: true, default: 0 },
        campo62_condicional: { type: "int", nullable: true, default: 0 },
        campo63_condicional: { type: "decimal", precision: 5, scale: 2, nullable: true, default: 0 },
        campo64_sueldo_imponible_salud: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo65_condicional: { type: "int", nullable: true, default: 0 },
        campo66_condicional: { type: "int", nullable: true, default: 0 },
        campo67_condicional: { type: "int", nullable: true, default: 0 },
        campo68_condicional: { type: "decimal", precision: 5, scale: 2, nullable: true, default: 0 },
        campo69_condicional: { type: "int", nullable: true, default: 0 },
        campo70_calculo_7_fonasa: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo71_mutualidad_isl: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo72_condicional: { type: "int", nullable: true, default: 0 },
        campo73_descuento_ips: { type: "int", nullable: true, default: 0 },
        campo74_condicional: { type: "int", nullable: true, default: 0 },
        campo75_codigo_isapre: { type: "int", nullable: true, default: 0 },
        campo76_num_contrato_salud: { type: "varchar", length: 16, nullable: true, default: "" },
        campo77_renta_imponible_trabajador: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo78_tipo_moneda: { type: "int", nullable: true, default: 0 },
        campo79_cotizacion_pactada: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo80_cotizacion_7_por_ciento: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo81_diferencia_7_por_ciento: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo82_condicional: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo83_codigo_ccaf: { type: "int", nullable: true, default: 0 },
        campo84_renta_imponible_ccaf: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo85_creditos_personales_ccaf: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo86_descuento_dental_ccaf: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo87_descuentos_leasing: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo88_descuento_seguro_vida_ccaf: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo89_otros_descuentos_ccaf: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo90_cotizacion_ccaf_no_isapre: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo91_descuento_cargas_familiares_ccaf: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo92_condicional: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo93_condicional: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo94_condicional: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo95_condicional: { type: "varchar", length: 20, nullable: true, default: "" },
        campo96_codigo_mutualidad: { type: "int", nullable: true, default: 0 },
        campo97_renta_imponible_mutual: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo98_calculo_mutual: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo99_condicional: { type: "int", nullable: true, default: 0 },
        campo100_renta_imponible_seg_cesantia: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo101_aporte_trabajador_seg_cesantia: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo102_aporte_empleador_seg_cesantia: { type: "decimal", precision: 8, scale: 2, nullable: true, default: 0 },
        campo103_condicional: { type: "int", nullable: true, default: 0 },
        campo104_condicional: { type: "varchar", length: 1, nullable: true, default: "" },
        campo105_condicional: { type: "varchar", length: 20, nullable: true, default: "" }
    },
    relations: {
        usuario: {
            target: "Usuario",
            type: "many-to-one",
            joinColumn: {
                name: "usuario_id"
            },
            onDelete: "CASCADE"
        },
        negocio: {
            target: "Negocio",
            type: "many-to-one",
            joinColumn: {
                name: "negocio_id"
            },
            onDelete: "CASCADE"
        }
    }
});